city_dict_cvMarket = {
    'Vilnius': '134',
    'Kaunas': '135',
    'Klaipėda': '136',
    'Šiauliai': '137',
    'Panevėžys': '138',
    'Alytus': '282',
}

job_category_dict_cvMarket = {
    'Visos kategorijos': '-1',
    'Administravimas': '2',
    'Apsauga': '16',
    'Aptarnavimas': '18',
    'Bankai / Draudimas': '38',
    'Dizainas / Kultūra / Pramogos': '12',
    'Elektronika / Telekomunikacijos': '4',
    'Energetika / Gamtos ištekliai': '5',
    'Finansai': '6',
    'Informacija / Žiniasklaida': '7',
    'Informacinės technologijos': '8',
    'Maitinimas': '20',
    'Marketingas / Reklama / RsV': '23',
    'Mechanika / Inžinerija': '14',
    'Pardavimai / Pirkimai': '15',
    'Personalo valdymas / Mokymai': '11',
    'Pramonė / Gamyba': '24',
    'Savanorystė / Praktika': '37',
    'Statyba / Nekilnojamasis turtas': '3',
    'Sveikata / Medicina / Farmacija': '19',
    'Švietimas / Moksliniai tyrimai': '25',
    'Teisė': '36',
    'Transportas / Logistika / Sandėliavimas': '21',
    'Turizmas / Viešbučiai': '22',
    'Vadovavimas / Verslo vystymas': '9',
    'Valstybinė tarnyba': '17',
    'Žemės ūkis / Miškininkystė / Gyvulininkystė': '13',
}


job_category_dict_cvOnline = {
    'Informacinės technologijos': 'INFORMATION_TECHNOLOGY',
    'Paslaugos / klientų aptarnavimas': 'SERVICE_INDUSTRY',
    'Finansai / apskaita': 'FINANCE_ACCOUNTING',
    'Organizavimas / valdymas': 'ORGANISATION_MANAGEMENT',
    'Gamyba / Pramonė': 'PRODUCTION_MANUFACTURING',
    'Bankai / draudimas': 'BANKING_INSURANCE',
    'Inžinerija': 'TECHNICAL_ENGINEERING',
    'Administravimas': 'ADMINISTRATION',
    'Pardavimai': 'SALES',
    'Prekyba / pirkimai / tiekimas': 'TRADE',
    'Transportas / logistika': 'LOGISTICS_TRANSPORT',
    'Elektronika / telekomunikacijos': 'ELECTRONICS_TELECOM',
    'Žmogiškieji ištekliai': 'HUMAN_RESOURCES',
    'Rinkodara / reklama': 'MARKETING_ADVERTISING',
    'Teisė': 'LAW_LEGAL',
    'Statyba / nekilnojamas turtas': 'CONSTRUCTION_REAL_ESTATE',
    'Energetika': 'ENERGETICS_ELECTRICITY',
    'Valstybinis / viešasis adminstravimas': 'STATE_PUBLIC_ADMIN',
    'Kokybės kontrolė': 'QUALITY_ASSURANCE',
    'Švietimas / mokslas': 'EDUCATION_SCIENCE',
    'Žiniasklaida / ryšys su visuomene': 'MEDIA_PR',
    'Praktika': 'INTERNSHIP',
    'Turizmas / viešbučiai / maitinimas': 'TOURISM_HOTELS_CATERING',
    'Medicina / socialinė rūpyba': 'HEALTH_SOCIAL_CARE',
    'Apsauga / gelbėjimo paslaugos / gynyba': 'SECURITY_RESCUE_DEFENCE',
    'Žemės ūkis / aplinkosauga': 'AGRICULTURE_ENVIRONMENTAL',
    'Kultūra / pramogos / sportas': 'CULTURE_ENTERTAINMENT',
    'Farmacija': 'PHARMACY',
    'Trečiasis sektorius / NVO': 'THIRD_SECTOR',
    'Miškininkystė / medienos apdirbimas': 'FOREST_WOODCUTTING',
    'Sezoninis': 'SEASONAL',
    'Savanoriškas darbas': 'VOLUNTARY',
}

city_dict_cvOnline = {
    'Vilnius': '540',
    'Kaunas': '501',
    'Klaipėda': '505',
    'Šiauliai': '528',
    'Panevėžys': '517',
    'Alytus': '488',
}
